version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store_manager
      MYSQL_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: node_app
    environment:
      NODE_APP_HOST: db
      NODE_PORT: 3000
      MYSQL_HOST: db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: store_manager
      SECRET_KEY: secretKey
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db_data:
